### ISSUE TITLE
Audio Integration

### ISSUE THREAD

**Issue by dhedner** [Lorenzo-St/HyjakProject#3]
The game build must demonstrate a functioning audio pipeline. Tasks include:
- Integrating Wwise into the Unreal Project.
- Providing proof of a functioning audio pipeline (at least one AkAudio event playing in the game build).

**Comment by Lorenzo-St** [comment]
Strike team members:
 - Avery
 - Ryder
If needed
 - Avi
 - Bruce
 - Javi
