### ISSUE TITLE
Initial Project Documentation

### ISSUE THREAD

**Issue by dhedner** [Lorenzo-St/HyjakProject#4]
Documentation for the game's starting point in terms of visuals, mechanics, and production. Tasks include:
- Prototype treatment of a refined concept
- Mechanics documentation for core gameplay vision
- Production methodology and management tool
- Repeatable build instructions to build the game reliably from source control
- Visual style guide of reference material, concept art, color scripts, etc.
- Art tech guidelines for naming schemes, software used, formatting, etc.
- Audio changelist for source check-in by audio engineers
- Audio style guide for concepts, examples, production documents, etc.

**Comment by Lorenzo-St** [comment]
Strike team members:
 - David
 - Irene
 - Lorenzo
 - Harley
 - Justin
 - Avery
