### ISSUE TITLE
Combat Design

### ISSUE THREAD

**Issue by dhedner** [Lorenzo-St/HyjakProject#5]
Establish a concise design for the game's various systems as they relate to core combat. Tasks include:
- Determining the full game loop
- Deciding on core input and controls
- ASF considerations, interactions, and reactions
- Building core systems and determining the technical/artistic needs for them
- Creating a list of desired combos
- An overview of the UI during gameplay

**Comment by Lorenzo-St** [comment]
Strike team members: 
 - Arthur
 - Adam
 - Avi
 - Justin
 - Javi
 - Kip
 - Anya
