### ISSUE TITLE
Character Design

### ISSUE THREAD

**Issue by dhedner** [Lorenzo-St/HyjakProject#6]
Initial character concepts are established with visual, behavioral, and mechanical considerations given to developing the game around them. Tasks include:
- Some forms of concept art for visual style
- Behavioral concepts related to a character controller (FSM, behavior trees, etc.)
- Enemy and NPC concepts with the same considerations given

**Comment by Lorenzo-St** [comment]
Strike Team members are: 
 - Dylan
 - Lorenzo
 - Arnold
 - Ryder
 - Annika
 - Dakota
 - Harley
 - Kip
 - Anya
 - Irene
