### ISSUE TITLE
Level Concept

### ISSUE THREAD

**Issue by dhedner** [Lorenzo-St/HyjakProject#7]
Concepts for the environment design and level layout. Tasks include:
- Collecting ideas and concepts for the design of the environment
- Considering level design in relation to the game's core loop and pacing

**Comment by Lorenzo-St** [comment]
Strike team members are:
 - Lorenzo
 - Kip
 - Modem
 - Anya
 - Ethen
 - Bryce
 - Yakshin
 - Irene
